/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

import java.util.Scanner;

public class App {

  public static Boolean playAgain;
  public static int score;
  
  public App(){
    playAgain = true;
  }

  // public void takeInput(Game letsplay){
  //   Boolean invalidChar = false;
  //   System.out.println();
  //   System.out.println();
  //   System.out.print("Insert a chatacter [A-Z] and press enter: ");
  //   Scanner letterInputScanner = new Scanner(System.in);
  //   String letterInput = letterInputScanner.nextLine();
  //   if(letterInput.matches("[A-Za-z]")){
  //     letterInput.toUpperCase();
  //     Character letterFromUser = Character.valueOf(letterInput.charAt(0));
  //     letsplay.guessLetter(letterFromUser);
  //     letsplay.printStats();
  //   } else {
  //     letsplay.printStats();
  //     invalidChar = true;
  //   }
  //   System.out.print(letterInput.toUpperCase()); //continúa o finaliza el printstats
  //   if (invalidChar){
  //     System.out.print(" \u001B[47m\u001B[30m<-- Please insert just one letter (from A to Z) at a time\u001B[0m");
  //   }
  //   System.out.println();
  // }

  // public void wannaPlayAgain(){
  //   Boolean invalidCharPlayAgain;
  //   Game.clearScreen();
  //   do{
  //     System.out.println("\u001B[44mTotal score: " + App.score + "\u001B[0m");
  //     System.out.println();
  //     System.out.println("\u001B[31m\u2665 = 10 pts/each\u001B[0m");
  //     System.out.println("\u001B[41mFLAWLESS VICTORY\u001B[0m = BONUS! +50 pts");
  //     System.out.println();
  //     System.out.println();
  //     System.out.print("Play Again? [Y]/[N]: ");
  //     Scanner playAgainScanner = new Scanner(System.in);
  //     String letterInput = playAgainScanner.nextLine();
  //     if(letterInput.matches("[yY]")){
  //       App.playAgain = true;
  //       invalidCharPlayAgain = false;
  //     } else if (letterInput.matches("[nN]")) {
  //       App.playAgain = false;
  //       invalidCharPlayAgain = false;
  //     } else {
  //       invalidCharPlayAgain = true;
  //     }
  //     if (invalidCharPlayAgain){
  //       Game.clearScreen();
  //       System.out.print("\u001B[47m\u001B[30mPlease input [Y] for YES to continue or [N] to exit.\u001B[0m");
  //     }
  //     System.out.println();
  //   } while (invalidCharPlayAgain);
  // }

    public void playerInput(Player thePlayer, Game theGame){
      thePlayer.takeInput(theGame);
        if (theGame.isGameWon()){
          thePlayer.score = thePlayer.score + 10*theGame.failCounter;
          if (theGame.failCounter == theGame.roundsPerGame){
            thePlayer.score = thePlayer.score + 50;
          }
      }
    }

  public static void main(String[] args) {
    App theGame = new App();
    Game letsplayplayer1 = new Game();
    Game letsplayplayer2 = new Game();
    Player player1 = new Player("María", letsplayplayer1);
    //Player player2 = new Player("Pedro", letsplayplayer2);
    //App nuevapp = new App();
    do{
      letsplayplayer1.resetGame();

      //letsplayplayer2.resetGame();

      do{
        theGame.playerInput(player1, letsplayplayer1);

        //theGame.playerInput(player2, letsplayplayer2);

        // player1.takeInput(letsplayplayer1);
        // if (letsplayplayer1.isGameWon()){
        //   player1.score = player1.score + 10*letsplayplayer1.failCounter;
        //   if (letsplayplayer1.failCounter == letsplayplayer1.roundsPerGame){
        //     player1.score = player1.score + 50;
        //   }
        // }
      } while (!letsplayplayer1.isGameWon() && !letsplayplayer1.isGameLost());
      try {
        System.out.println();
        System.out.println();
        System.out.print("\u001B[47m\u001B[30mPress enter to continue.\u001B[0m");
        Scanner letterInputScanner = new Scanner(System.in);
        letterInputScanner.nextLine();
      } catch (Exception e) {}
      player1.wannaPlayAgain();
    } while (player1.playAgain); //TIENES QUE CAMBIAR ESTO A UN AGREEMENT
    Game.clearScreen();
  }
}
