/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

import org.junit.Test;
// import static org.junit.Assert.*;

import org.junit.Ignore;

public class AppTest {
    @Ignore
    @Test public void appHasAGreeting() {
        // App classUnderTest = new App();
        // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
